# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "c0f689d9-8f35-4699-b478-949faa2c5870",
# META       "default_lakehouse_name": "source",
# META       "default_lakehouse_workspace_id": "ccb26ac4-9887-4f7d-892e-2d3d972b14ff",
# META       "known_lakehouses": [
# META         {
# META           "id": "c0f689d9-8f35-4699-b478-949faa2c5870"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# # nb_log_start
# **Called by:** All Fabric Pipelines at the START of every run.
# 
# Writes a `RUNNING` entry to:
# - `batch_control` — registers the batch as in-flight
# - `pipeline_run_log` — creates the audit trail entry
# 
# > This notebook is called **before** the transform notebook runs.
# > If a batch is stuck as RUNNING, it means the transform crashed without reaching nb_log_end.

# MARKDOWN ********************

# ## 1. Parameters
# Injected by Fabric Pipeline at runtime.

# PARAMETERS CELL ********************

batch_id      = ''   # UUID generated by pipeline Set Variable activity
pipeline_name = ''   # must match pipeline_control.pipeline_name
layer         = ''   # BRONZE | SILVER | GOLD
source_system = ''   # source identifier
source_file   = ''   # source file path (Bronze only, empty string for Silver/Gold)

print(f'batch_id      : {batch_id}')
print(f'pipeline_name : {pipeline_name}')
print(f'layer         : {layer}')
print(f'source_system : {source_system}')
print(f'source_file   : {source_file}')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## 2. Imports

# CELL ********************

from pyspark.sql.types import (
    StructType, StructField, StringType, IntegerType, TimestampType, LongType
)
from datetime import datetime
import uuid

spark.conf.set('spark.sql.session.timeZone', 'UTC')
run_start = datetime.utcnow()
print(f'run_start : {run_start}')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## 3. Insert into `batch_control` (status = RUNNING)

# CELL ********************

schema = StructType([
    StructField('batch_id',        StringType(),    False),
    StructField('pipeline_name',   StringType(),    False),
    StructField('layer',           StringType(),    False),
    StructField('source_system',   StringType(),    True),
    StructField('source_file',     StringType(),    True),
    StructField('status',          StringType(),    False),
    StructField('retry_count',     IntegerType(),   False),
    StructField('rows_read',       LongType(),      True),
    StructField('rows_written',    LongType(),      True),
    StructField('rows_failed',     LongType(),      True),
    StructField('error_message',   StringType(),    True),
    StructField('batch_start_dts', TimestampType(), True),
    StructField('batch_end_dts',   TimestampType(), True),
    StructField('created_dts',     TimestampType(), False),
    StructField('updated_dts',     TimestampType(), False),
])

row = [(
    batch_id, pipeline_name, layer, source_system,
    source_file if source_file else None,
    'RUNNING', 0,
    None, None, None, None,
    run_start, None,
    run_start, run_start
)]

spark.createDataFrame(row, schema=schema) \
     .write.format('delta').mode('append').saveAsTable('batch_control')

print(f'[batch_control] Inserted: {batch_id} | {layer} | RUNNING')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## 4. Insert into `pipeline_run_log` (status = RUNNING)

# CELL ********************

# Lookup notebook_name from pipeline_control
meta = spark.sql(f"""
    SELECT notebook_name
    FROM   pipeline_control
    WHERE  pipeline_name = '{pipeline_name}'
""").collect()

notebook_name = meta[0]['notebook_name'] if meta else 'unknown'

log_schema = StructType([
    StructField('log_id',           StringType(),    False),
    StructField('batch_id',         StringType(),    False),
    StructField('pipeline_name',    StringType(),    False),
    StructField('layer',            StringType(),    False),
    StructField('source_system',    StringType(),    True),
    StructField('notebook_name',    StringType(),    True),
    StructField('status',           StringType(),    False),
    StructField('run_start_dts',    TimestampType(), True),
    StructField('run_end_dts',      TimestampType(), True),
    StructField('duration_seconds', LongType(),      True),
    StructField('rows_read',        LongType(),      True),
    StructField('rows_written',     LongType(),      True),
    StructField('rows_failed',      LongType(),      True),
    StructField('error_message',    StringType(),    True),
    StructField('retry_attempt',    IntegerType(),   True),
    StructField('created_dts',      TimestampType(), False),
])

log_row = [(
    str(uuid.uuid4()), batch_id, pipeline_name, layer,
    source_system, notebook_name, 'RUNNING',
    run_start, None, None,
    None, None, None, None,
    0, run_start
)]

spark.createDataFrame(log_row, schema=log_schema) \
     .write.format('delta').mode('append').saveAsTable('pipeline_run_log')

print(f'[pipeline_run_log] Inserted: {batch_id} | {layer} | RUNNING')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ## 5. Exit — pass run_start back to pipeline

# CELL ********************

# Pipeline captures this to calculate duration in nb_log_end
mssparkutils.notebook.exit(str(run_start))
print(f'nb_log_start complete. run_start={run_start}')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
