# Fabric notebook source

# METADATA ********************

# META {
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "c0f689d9-8f35-4699-b478-949faa2c5870",
# META       "default_lakehouse_name": "source",
# META       "default_lakehouse_workspace_id": "ccb26ac4-9887-4f7d-892e-2d3d972b14ff",
# META       "known_lakehouses": [
# META         {
# META           "id": "c0f689d9-8f35-4699-b478-949faa2c5870"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# # nb_00_framework_setup
# **Run once** to bootstrap the 3 control tables in the attached `source` lakehouse.

# | Table | Role |
# |---|---|
# | `pipeline_control` | Static registry of all registered pipelines |
# | `batch_control` | One row per batch per layer — the live work queue |
# | `pipeline_run_log` | Append-only audit log per execution attempt |

# ### Batch lifecycle
# ```
# Pipeline_Bronze  → creates batch_id  → batch_control (layer=BRONZE, status=PENDING→RUNNING→SUCCESS)
# Pipeline_Silver  → finds BRONZE_SUCCESS batches not yet in SILVER → processes → SILVER_SUCCESS
# Pipeline_Gold    → finds SILVER_SUCCESS batches not yet in GOLD   → processes → GOLD_SUCCESS
# ```

# MARKDOWN ********************

# ## 1. Imports

# CELL ********************

from pyspark.sql.types import (
    StructType, StructField,
    StringType, IntegerType, TimestampType, LongType, BooleanType
)
from datetime import datetime
import uuid

spark.conf.set('spark.sql.session.timeZone', 'UTC')
print(f'Active DB : {spark.catalog.currentDatabase()}')
print(f'Spark     : {spark.version}')

# MARKDOWN ********************

# ## 2. Create `pipeline_control`
Static registry — one row per registered pipeline. Updated manually when new pipelines are onboarded.

# CELL ********************

schema = StructType([
    StructField('pipeline_id',     StringType(),  False),  # UUID
    StructField('pipeline_name',   StringType(),  False),  # unique name e.g. bronze_ingest_sales
    StructField('source_system',   StringType(),  True),   # source identifier
    StructField('layer',           StringType(),  False),  # BRONZE | SILVER | GOLD
    StructField('execution_order', IntegerType(), False),  # run order within layer
    StructField('notebook_name',   StringType(),  True),   # Fabric notebook display name
    StructField('target_table',    StringType(),  True),   # destination Delta table
    StructField('is_active',       BooleanType(), False),  # false = skip this pipeline
    StructField('max_retries',     IntegerType(), False),
    StructField('created_dts',     TimestampType(), False),
    StructField('updated_dts',     TimestampType(), False),
])

now = datetime.utcnow()

# ── Seed: register your pipelines here ──────────────────────────────────────
rows = [
    (str(uuid.uuid4()), 'bronze_ingest_sales',      'source_system', 'BRONZE', 1, 'nb_01_bronze_ingest',    'bronze_sales',      True, 3, now, now),
    (str(uuid.uuid4()), 'silver_transform_sales',   'source_system', 'SILVER', 1, 'nb_02_silver_transform', 'silver_sales',      True, 3, now, now),
    (str(uuid.uuid4()), 'gold_dim_product',         'source_system', 'GOLD',   1, 'nb_03_gold_load',        'gold_dim_product',  True, 3, now, now),
    (str(uuid.uuid4()), 'gold_fact_sales',          'source_system', 'GOLD',   2, 'nb_03_gold_load',        'gold_fact_sales',   True, 3, now, now),
]

df = spark.createDataFrame(rows, schema=schema)
df.write.format('delta').mode('overwrite').option('overwriteSchema', 'true').saveAsTable('pipeline_control')

print('✅ pipeline_control created.')
spark.sql('SELECT pipeline_name, layer, execution_order, notebook_name, target_table FROM pipeline_control ORDER BY layer, execution_order').show(truncate=False)

# MARKDOWN ********************

# ## 3. Create `batch_control`
One row per batch per layer. This is the **live work queue** that Silver and Gold pipelines query to find unprocessed batches.

# CELL ********************

schema = StructType([
    StructField('batch_id',          StringType(),    False),  # UUID — generated by Bronze pipeline
    StructField('pipeline_name',     StringType(),    False),  # FK to pipeline_control
    StructField('layer',             StringType(),    False),  # BRONZE | SILVER | GOLD
    StructField('source_system',     StringType(),    True),
    StructField('source_file',       StringType(),    True),   # source file name if applicable
    StructField('status',            StringType(),    False),  # PENDING | RUNNING | SUCCESS | FAILED
    StructField('retry_count',       IntegerType(),   False),
    StructField('rows_read',         LongType(),      True),
    StructField('rows_written',      LongType(),      True),
    StructField('rows_failed',       LongType(),      True),
    StructField('error_message',     StringType(),    True),
    StructField('batch_start_dts',   TimestampType(), True),
    StructField('batch_end_dts',     TimestampType(), True),
    StructField('created_dts',       TimestampType(), False),
    StructField('updated_dts',       TimestampType(), False),
])

df = spark.createDataFrame([], schema=schema)
df.write.format('delta').mode('overwrite').option('overwriteSchema', 'true').saveAsTable('batch_control')

print('✅ batch_control created (empty — Bronze pipeline will insert rows at runtime).')
spark.sql('DESCRIBE batch_control').show(truncate=False)

# MARKDOWN ********************

# ## 4. Create `pipeline_run_log`
Append-only. Every execution attempt writes one row here — success or failure.

# CELL ********************

schema = StructType([
    StructField('log_id',            StringType(),    False),  # UUID per log entry
    StructField('batch_id',          StringType(),    False),  # FK to batch_control
    StructField('pipeline_name',     StringType(),    False),
    StructField('layer',             StringType(),    False),
    StructField('source_system',     StringType(),    True),
    StructField('notebook_name',     StringType(),    True),
    StructField('status',            StringType(),    False),  # RUNNING | SUCCESS | FAILED
    StructField('run_start_dts',     TimestampType(), True),
    StructField('run_end_dts',       TimestampType(), True),
    StructField('duration_seconds',  LongType(),      True),
    StructField('rows_read',         LongType(),      True),
    StructField('rows_written',      LongType(),      True),
    StructField('rows_failed',       LongType(),      True),
    StructField('error_message',     StringType(),    True),
    StructField('retry_attempt',     IntegerType(),   True),
    StructField('created_dts',       TimestampType(), False),
])

df = spark.createDataFrame([], schema=schema)
df.write.format('delta').mode('overwrite').option('overwriteSchema', 'true').saveAsTable('pipeline_run_log')

print('✅ pipeline_run_log created (empty — ready for appends).')
spark.sql('DESCRIBE pipeline_run_log').show(truncate=False)

# MARKDOWN ********************

# ## 5. Verify All Tables

# CELL ********************

for tbl in ['pipeline_control', 'batch_control', 'pipeline_run_log']:
    count = spark.sql(f'SELECT COUNT(*) AS cnt FROM {tbl}').collect()[0]['cnt']
    print(f'  {tbl:30s} → {count} rows')

print('\n✅ Framework setup complete. Run nb_01_bronze_ingest to start your first batch.')
